SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE `TbShows` (
  `ID` int(11) NOT NULL,
  `ShowDescription` varchar(300) NOT NULL,
  `PresentedBy` varchar(300) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

CREATE TABLE `TbSongs` (
  `ID` int(11) NOT NULL,
  `Title` varchar(300) NOT NULL,
  `Artist` varchar(300) NOT NULL,
  `PlayCount` int(11) NOT NULL,
  `ChartPlacings` int(11) DEFAULT NULL,
  `Link` varchar(300) NOT NULL,
  `Import` tinyint(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

CREATE TABLE `TbSongsShows` (
  `ID` int(11) NOT NULL,
  `SongID` int(11) NOT NULL,
  `ShowID` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;


ALTER TABLE `TbShows`
  ADD PRIMARY KEY (`ID`);

ALTER TABLE `TbSongs`
  ADD PRIMARY KEY (`ID`);

ALTER TABLE `TbSongsShows`
  ADD PRIMARY KEY (`ID`),
  ADD KEY `TvSongsShows_SongID_to_tbSongs_Id` (`SongID`),
  ADD KEY `TvSongsShows_ShowID_to_tbshow_Id` (`ShowID`);


ALTER TABLE `TbShows`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `TbSongs`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `TbSongsShows`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT;


ALTER TABLE `TbSongsShows`
  ADD CONSTRAINT `TvSongsShows_ShowID_to_tbshow_Id` FOREIGN KEY (`ShowID`) REFERENCES `TbShows` (`ID`) ON DELETE CASCADE,
  ADD CONSTRAINT `TvSongsShows_SongID_to_tbSongs_Id` FOREIGN KEY (`SongID`) REFERENCES `TbSongs` (`ID`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
